openai:
  model: ${OPEN_AI_MODEL}
  api:
    key: ${OPEN_AI_KEY}
    url: ${OPEN_AI_URL}

image:
  upload:
    url: ${IMAGE_UPLOAD_URL}
    directory: ${IMAGE_UPLOAD_DIRECTORY}

lmm:
  openapi:
    url: http://localohst:8080